version: "3.7"

services:
  database:
    container_name: pg14
    image: postgres:14.6
    restart: always
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
      PGDATA: /var/lib/postgresql/data
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:6.15
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@linuxhint.com
      PGADMIN_DEFAULT_PASSWORD: secret
      # host name/address: host.docker.internal
      PGADMIN_LISTEN_PORT: 80
    ports:
      - "8800:80"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    depends_on:
      - database
volumes:
  db-data:
  pgadmin-data:
