version: "3.7"

services:
  database:
    container_name: database
    image: postgres:13.8-alpine
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: postgres
      PGDATA: /var/lib/postgresql/data
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5488:5432"

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:6.15
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@linuxhint.com
      PGADMIN_DEFAULT_PASSWORD: secret
      PGADMIN_LISTEN_PORT: 80
    ports:
      - "8888:80"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    links:
      - "database:pgsql-server"
    depends_on:
      - database

volumes:
  db-data:
  pgadmin-data:

# guide https://linuxhint.com/postgresql_docker/
# browser
# http://192.168.0.37:8888 admin@linuxhint.com secret
