ALTER TABLE "ORDERS" DROP CONSTRAINT IF EXISTS "ORDERS_fk0";

ALTER TABLE "PRODUCTS" DROP CONSTRAINT IF EXISTS "PRODUCTS_fk0";

ALTER TABLE "CATEGORIES" DROP CONSTRAINT IF EXISTS "CATEGORIES_fk0";

ALTER TABLE "SHIPPERS" DROP CONSTRAINT IF EXISTS "SHIPPERS_fk0";

ALTER TABLE "SUPPLIES" DROP CONSTRAINT IF EXISTS "SUPPLIES_fk0";

ALTER TABLE "SHIPPERS_SUPPLIES" DROP CONSTRAINT IF EXISTS "SHIPPERS_SUPPLIES_fk0";

ALTER TABLE "SHIPPERS_SUPPLIES" DROP CONSTRAINT IF EXISTS "SHIPPERS_SUPPLIES_fk1";

ALTER TABLE "MANAGERS" DROP CONSTRAINT IF EXISTS "MANAGERS_fk0";

ALTER TABLE "CLIENTS" DROP CONSTRAINT IF EXISTS "CLIENTS_fk0";

ALTER TABLE "DELIVERIES" DROP CONSTRAINT IF EXISTS "DELIVERIES_fk0";
